colors:
  # Default colors
  primary:
    background: '{background}'
    foreground: '{foreground}'

    dim_foreground:    '{color8}'
    bright_foreground: '{color12}'
    dim_background:    '{color8}' # not sure
    bright_background: '{background}' # not sure

  # Cursor colors
  # cursor:
    # text:   '{foreground}'
    # cursor: '{background}'

  # Normal colors
  normal:
    black:   '{color0}'
    red:     '{color1}'
    green:   '{color2}'
    yellow:  '{color3}'
    blue:    '{color4}'
    magenta: '{color5}'
    cyan:    '{color6}'
    white:   '{color7}'

  # Bright colors
  bright:
    black:   '{color8}'
    red:     '{color9}'
    green:   '{color10}'
    yellow:  '{color11}'
    blue:    '{color12}'
    magenta: '{color13}'
    cyan:    '{color14}'
    white:   '{color15}'

  # Dim colors
  dim:
    black:   '{color0}'
    red:     '{color1}'
    green:   '{color2}'
    yellow:  '{color3}'
    blue:    '{color4}'
    magenta: '{color5}'
    cyan:    '{color6}'
    white:   '{color7}'
